✨ macOS Media Integration
ytmdesktop/ytmdesktop pull request #637
Opened 2021-02-23 17:17 UTC by mkotb

✨ Media Touchbar Support
🐛 Broken media hotkeys (play/next/prev) on new versions of macOS

This PR adds integration with macOS' media system, since in newer versions of macOS, it appears that this is required for any of the media keys to work. This also has the nice addition of allowing YTM to be interacted with through the Touchbar in other apps as well as the new Control Center in macOS Big Sur.

2021-02-25 19:36 UTC, mingjun97 commented
I'm little busy recently. I'll review this PR when I'm free. Thanks for your contribution!

2021-03-07 15:39 UTC, poxtron commented
Upvote ⬆️ 😁

2021-03-09 21:16 UTC, NovusTheory commented
Cross posting https://github.com/ytmdesktop/ytmdesktop/issues/652#issuecomment-793631400

2021-03-17 14:37 UTC, adlerluiz commented
@mingjun97 could you take the test?

2021-03-17 22:30 UTC, mingjun97 commented
> @mingjun97 could you take the test?

I have deadline today. I'll review this PR after I'm done. :)

2021-03-18 19:56 UTC, adlerluiz commented
no problem, thanks =)

2021-03-19 18:38 UTC, chadxz commented
running this PR locally, I'm able to use my Airpods pro to control playback, which I was previously having trouble with. So, thank you 💯

2021-03-22 19:59 UTC, akinnee commented
Looks like this might fix my issue. My touchbar media keys stopped working recently.

2021-03-22 23:01 UTC, mingjun97 commented
![image](https://user-images.githubusercontent.com/15214491/112068463-31c65900-8b27-11eb-8d5e-902c475a0f61.png)

I found these issues. 🤔 

1. Play/Pause Icon not sync with ytmdesktop
2. The album cover not sync to the touchbar control
3. The progress(current time / duration) not sync to the touchbar control.

Are these issues left intentionaly right now, or not fixable?

Again, thanks for your contribution to ytmdesktop. :)

2021-03-22 23:15 UTC, mkotb commented
Only #2 is intentional -- it is displaying the current app icon, since
you're running the dev build it's the generic file icon.

The other two aren't. If you build for production, do you still have those
issues? It works on my machine.

On Mon, Mar 22, 2021, 4:02 PM mingjun97 ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/15214491/112068463-31c65900-8b27-11eb-8d5e-902c475a0f61.png>
>
> I found these issues. 🤔
>
>    1. Play/Pause Icon not sync with ytmdesktop
>    2. The album cover not sync to the touchbar control
>    3. The progress(current time / duration) not sync to the touchbar
>    control.
>
> Are these issues left intentionaly right now, or not fixable?
>
> Again, thanks for your contribution to ytmdesktop. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ytmdesktop/ytmdesktop/pull/637#issuecomment-804451419>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQRX4U6FJDLNBX6CIXAHM3TE7D7HANCNFSM4YC37VFA>
> .
>

2021-03-23 04:11 UTC, mingjun97 commented
Could you build a production version for me? The production I built still has issue 1 and 3.

For reproduce issue 1, I just simple touch the play icon on touch bar twice. 😂
For issues 3, I build a production version and it just not work.(btw, I'm using roseta on M1 MacBook Pro).

2021-04-09 18:37 UTC, cmcpasserby commented
any progression on getting this merged in?

2021-04-21 19:09 UTC, adlerluiz commented
unfortunately I don't have a mac to test, so if you can perform a test and report how it is, thank you

2021-05-03 05:47 UTC, twolfson commented
Tested this on 2019 Intel MBP. Seems to work great, steps I took listed below:

```bash
# Clone our repo
git clone https://github.com/ytmdesktop/ytmdesktop
cd ytmdesktop

# Modify .git/config
[remote "upstream-pr"]
        url = https://github.com/ytmdesktop/ytmdesktop
        fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*

# Fetch PRs
git fetch upstream-pr

# Install our dependencies (prob redundant but was in frustrated state)
yarn install
npm install

# Rebuild and formally build (prob redundant but was in frustrated state)
npm run rebuild
npm run build:mac

# Launch our development build
open dist/mac/YouTube\ Music\ Desktop\ App.app/

# Verified touchbar works 🎉
```

2021-05-06 09:27 UTC, DanielSaunders commented
Just confirming this works for me as well. I followed the steps provided by Todd above on my own 2019 Intel MBP. The touchbar controls work and the progress/state of the playing song syncs to the touchbar. The only minor issue is that the album art still does not sync to the touchbar.

The media controls on my external keyboard work now as well, which is why I was originally looking for a fix.

2021-05-09 21:00 UTC, mingjun97 requested changes
Please make the dependency `tidal-engineering/electron-media-service` optional since it only used in macOS variant now.

Thanks!

2021-05-09 21:00 UTC, mingjun97 commented on package.json
> +        "electron-media-service": "github:tidal-engineering/electron-media-service",
Please move this dependency into `optionalDependencies` segment, since it's only used in macOS currently. Thanks!

2021-05-09 21:00 UTC, mingjun97 commented on package-lock.json
> +            "version": "github:tidal-engineering/electron-media-service#4fdb3d43a74b274a53261b11aa5c11a4f5a9d62f",
add `"optional": true,` here.

2021-05-09 21:00 UTC, mingjun97 commented on yarn.lock
> +
make it optional here.

2021-06-16 14:01 UTC, cwhits commented
@mkotb any chance of getting those changes in so this can get merged? 🙏

2021-07-10 15:50 UTC, dm3ch commented
Hi,
I have just created PR with same changes. Fixed conflict with upstream development branch and made electron-media-service dependency optional, as proposed reviewer - https://github.com/ytmdesktop/ytmdesktop/pull/767

2023-03-20 20:33 UTC, merged